naamahdaemon/minaamah

src/components/NodePayouts/index.js
Add some mina foundation and investors locked accounts
=> Update payouts page

blog/2024-05-31-epoch-78-payouts/index.md
=> Add Blog post

blog/2024-05-31-Mina-Hard-Fork/index.md
=> Post blog post

blog/2024-06-07-epoch-78-79-payouts/index.md
Publish blog post about epoch 78 and 79 payouts
=> New blog post

src/components/EpochStats/index.js, src/components/EpochStats/styles.module.css
=> Update Epoch Stats CSS

src/components/EpochStats/index.js, src/components/EpochStats/styles.module.css
Add epoch progress bar customizations
=> Update epoch stat page

package-lock.json, package.json, src/components/EpochStats/index.js, src/components/EpochStats/styles.module.css, src/components/HomepageFeatures/index.js, src/components/TwitterFeed/TwitterFeed.js
Add Mina Twitter Feed to the homepage
=> Add Mina Twitter Feed to the homepage

src/components/HomepageFeatures/index.js
=> Disable twitter feed

i18n/fr/docusaurus-plugin-content-docs/current/01-Node Statistics/epoch_stats.md, i18n/fr/docusaurus-plugin-content-docs/current/01-Node Statistics/index.md
Update Node Stats FR index page
=> Update Node Stats FR index page

docusaurus.config.js, i18n/en/docusaurus-theme-classic/footer.json, i18n/fr/docusaurus-theme-classic/footer.json
https://github.com/naamahdaemon
=> Add Social network links to footer

blog/2024-01-10-welcome/index.md, i18n/fr/docusaurus-plugin-content-blog/2024-01-10-welcome/index.md
=> Update Welcome Blog post

docs/01-Node Statistics/payouts_simulator.md, src/components/PayoutSimulator/index.js, src/components/PayoutSimulator/styles.module.css
=> Add Payout Simulator

src/components/PayoutSimulator/index.js, static/payout-simulator.html
Temporary fix to delegators limit
=> Handle delegators limit

static/payout-simulator.html
Add Additional stake block creation impact
=> Update payout simulator

static/payout-simulator.html
Update Payout Simulator with history graph
=> Update Payout Simulator with history graph

static/payout-simulator.html
Change stake scale to mllions for display
=> Change stake scale to mllions for display

src/components/NodePayouts/index.js
Add new foundation delegation addresses
=> Update Payout calculator page

static/mina-graph/index.html
Add transaction details to side panel
=> Add transaction details to side panel

static/mina-graph/index.html
Move Data Slicer along with Side panel
=> Move Data Slicer along with Side panel

static/mina-graph/index.html
=> Fix service-worker ref

docs/06-Application Insights/index.md, docs/06-Application Insights/proof-of-research.md
Adding Proof of Research Application insight for a Proof of Useful Work using Mina Protocol
=> Add Proof of Research application insight
